* arctoolbox: Privacy policy

Welcome to the ArcToolbox app for Android!

This is an open source Android app developed by Fredrik Helmer. The
source code is available on GitHub under the MIT License

As an avid Android user myself, I take privacy very seriously.
I know how frustrating it is when apps collect your data without your knowledge.

** Data collected by the app

I hereby state, to the best of my knowledge and belief, that I have
not programmed this app to collect any personally identifiable
information. All data created by the you (the user) is stored locally
in your device (in shared preferences) and can be simply erased by
clearing the app's data or uninstalling it. No analytics software is
present in the app either.

** Explanation of permissions requested in the app

The list of permissions required by the app can be found in the `AndroidManifest.xml` file.

-  android.permission.ACCESS_FINE_LOCATION
-  android.permission.ACCESS_COARSE_LOCATION

They are only used to present the location in the app. Nothing is
stored anywhere.

If you find any security vulnerability that has been inadvertently
caused by me, or have any question regarding how the app protectes
your privacy, please send me an email or post a discussion on GitHub,
and I will surely try to fix it/help you.

Yours sincerely,
Fredrik Helmer
Lund, Sweden
support@helmer.se
